version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: social_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: social_db
    ports:
      - "3306:3306"
    volumes:
      # 自動載入你專案 DB 資料夾裡的 sql 檔進行初始化
      - ./DB:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  backend:

    build:
      context: .        # 上下文依然是專案根目錄（這樣才抓得到 pom.xml 和 mvnw）
      dockerfile: Dockerfile
    container_name: social_backend_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/social_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - db

  frontend:
    build:
      context: ./front  # 請對應你的前端資料夾名稱
      dockerfile: Dockerfile
    container_name: social_frontend_app
    ports:
      - "5173:80"  # 評審只要打開 http://localhost:5173 就能看到網頁
    depends_on:
      - backend