spring.datasource.url=jdbc:mysql://localhost:3306/esun_social?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=dbpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 如果你在本地端測試，可以加上這行讓每次啟動時自動檢查或更新 DDL（選填）
spring.jpa.hibernate.ddl-auto=update